### ISSUE TITLE
How do I grab the current time that is being displayed?

### ISSUE THREAD

**Issue by kElias-lrw** [vydimitrov/react-countdown-circle-timer#52] opened 2020-09-09 20:44 UTC
In my program, if they answer all the questions before the time is up I want it to display how fast they completed it, but I can't seem to grab the remainingTime. 

```jsx
const Timer = ({time, timerEnabled, iterIndex, completed}) => {
  const [currentTime, setCurrentTime] = React.useState(time);
  
  const renderTime = ({ remainingTime }) => {
    setCurrentTime(remainingTime);

    if (remainingTime === 0) {
      return <div className="timer">Too late...</div>;
    }
  
    return (
      <div className="timer">
        <div className="text">Remaining</div>
        <div className="value">{remainingTime}</div>
        <div className="text">seconds</div>
      </div>
    );
  };

  return (
    <div className="timer-wrapper">
      <CountdownCircleTimer
        isPlaying={iterIndex > 0}
        duration={time}
        colors={[["#004777", 0.33], ["#F7B801", 0.33], ["#A30000"]]}
        onComplete={timerEnabled ? () => completed(currentTime) : [false, 0]}
      >
        {renderTime}
      </CountdownCircleTimer>
    </div>
  );
};


```

**Comment by vydimitrov** [comment] 2020-09-10 07:04
Hey @kElias-lrw, I did a [https://codesandbox.io/s/quizzical-leaf-26vie?file=/src/index.js](quick demo in Codesanbox) where I update state in the `renderTime` function and it works as expected. I suspect that there is some other problem with your code. Could you please create new Codesandbox with your code and I will take a look on it.

By the way`onComplete` is eaither `function` or `undefined`, so you can do this:
```js
onComplete={timerEnabled ? () => completed(currentTime) : undefined}
```

**Comment by vydimitrov** [comment] 2020-09-15 06:46
Hey @kElias-lrw, I am closing this bug, let me know if you need any additional help.

**Closed by vydimitrov** 2020-09-15 06:46 UTC
Labels: help wanted, web

**Comment by Tristan1075** [comment] 2020-11-12 14:02
I tried your example code but i got this warning every seconds in react-native :/ 


![image](https://user-images.githubusercontent.com/31615425/98949364-e86e5900-24f7-11eb-848d-5449c5971b70.png)



```
const CountdownTimer: React.FC<Props> = (props) => {
  const {textSize, containerSize, strokeWidth, duration} = props;
  const [currentTime, setCurrentTime] = React.useState();

  const renderTime = ({remainingTime, elapsedTime}) => {
    setCurrentTime(remainingTime);
  };

  return (
    <View style={styles.container}>
      <CountdownCircleTimer
        isPlaying
        duration={duration ? duration : 999999}
        colors={duration ? Colors.circleCountDownColor : Colors.lightskyblue}
        size={containerSize}
        strokeWidth={strokeWidth}>
        {renderTime}
      </CountdownCircleTimer>
    </View>
  );
};
```

**Comment by vydimitrov** [comment] 2020-11-12 14:42
You should return something, like `null`, from `renderTime`

**Comment by rpsutton** [comment] 2021-01-10 00:27
@vydimitrov Is this not still setting state from within a rendered component? I believe the error persists.

**Comment by vydimitrov** [comment] 2021-01-10 11:23
@rpsutton, Is this about Web or Mobile? Please create a demo reproducing the issue I will take a look on it.

**Comment by rpsutton** [comment] 2021-01-10 14:43
The issue I am having is for Mobile (ios specifically, I have not tried Android). In this [quick demo I made](https://snack.expo.io/@flexhedge/react-native-countdown-circle-timer-issue-demo) there is seemingly no issue. However, when I try to implement the exact same code within an RN app on my machine, I receive this warning.
<img width="336" alt="Screen Shot 2021-01-10 at 9 39 03 AM" src="https://user-images.githubusercontent.com/57606697/104125906-b296f680-5327-11eb-99ec-cc7869fc798f.png">
I am now confused because I do not know if there is a problem or not, and I do not know why my machine shows a warning while the snack demo does not.

**Comment by vydimitrov** [comment] 2021-01-11 08:31
I'd suggest try to get the snack demo as close as possible to your app and you may find the issue. Let me know if I can help you somehow.
