### ISSUE TITLE
This coming when when leaving screen and coming back for another timer on same screen

### ISSUE THREAD

**Issue by Ajmal0197** [vydimitrov/react-countdown-circle-timer#39] opened 2020-07-18 19:35 UTC
TypeError: this._listeners[_key] is not a function. (In 'this._listeners[_key]({
            value: value
          })', 'this._listeners[_key]' is undefined)

__callListeners
    AnimatedNode.js:139:6
__callListeners
    AnimatedWithChildren.js:76:4
_updateValue
    AnimatedValue.js:246:4
animation.start$argument_1
    AnimatedValue.js:211:8
onUpdate
    TimingAnimation.js:144:4
onUpdate
    [native code]:0
_callTimer
    JSTimers.js:137:14
callTimers
    JSTimers.js:387:16
__callFunction
    MessageQueue.js:425:19
__guard$argument_0
    MessageQueue.js:112:6
__guard
    MessageQueue.js:373:10
callFunctionReturnFlushedQueue
    MessageQueue.js:111:4
callFunctionReturnFlushedQueue
    [native code]:0

**Comment by vydimitrov** [comment] 2020-07-19 06:38
Hey @Ajmal0197, thanks for reporting this issue. Could you please create a [Expo Snack](https://snack.expo.io/) reproducing the issue and I will try to investigate what is the cause?

**Comment by Ajmal0197** [comment] 2020-07-19 06:48
> Hey @Ajmal0197, thanks for reporting this issue. Could you please create a [Expo Snack](https://snack.expo.io/) reproducing the issue and I will try to investigate what is the cause?

Sorry but can't make the expo I am implementing on big project with Redux.
Actually i have to run 3 timers in background. I have managed it using 3 different reducer object state but when i delete any object and start the timer again for that object this error comes. Else the timer is working perfectly.

Is their anything else that can be done to run timer in background so that the user can navigate to different screens still the timer don't stop. If possible kindly help 😊
And thanks for replying

**Comment by vydimitrov** [comment] 2020-07-19 11:54
This sounds something very specific to your project so I am not sure if I can help you without seeing it. You can mock something quickly on ExpoSnack to get to the error. 

Other than that, the timer should not stop when you navigate to a different screen because it measures the elapsed time sine it started paying. Do you by any chance unmount the Screen when navigating to a new one?

**Comment by Ajmal0197** [comment] 2020-07-19 12:42
> This sounds something very specific to your project so I am not sure if I can help you without seeing it. You can mock something quickly on ExpoSnack to get to the error. 
> 
> Other than that, the timer should not stop when you navigate to a different screen because it measures the elapsed time sine it started paying. Do you by any chance unmount the Screen when navigating to a new one?

 
Okaye I don't know how to mock error in expo... I will try it possible..👍

Yes since their are multiple screen in my app whenever I use navigation.navigate timers resets else till navigation.push it's working fine.

Will try to figure out work around.
Thanks again for providing such a nice library 👍👍💯

**Comment by vydimitrov** [comment] 2020-07-20 07:22
I didn't mean mocking the error but rather mocking your complicated app, like add a few screens and switch between them. 

If you are unmounting the screens when navigatting between them then you also unmount the timer and that is why it looses state.  I would love to help you more but I will need to see some code :)

**Comment by Ajmal0197** [comment] 2020-07-20 18:47
> I didn't mean mocking the error but rather mocking your complicated app, like add a few screens and switch between them.
> 
> If you are unmounting the screens when navigatting between them then you also unmount the timer and that is why it looses state. I would love to help you more but I will need to see some code :)


[StartHeatingTime.js.zip](https://github.com/vydimitrov/react-countdown-circle-timer/files/4949500/StartHeatingTime.js.zip)

hi :)
sorry for late reply,
here is my code timer is running fine but gives error when reset the timer from reducer and then starting back again

**Comment by vydimitrov** [comment] 2020-07-21 07:24
Hey, thanks for prepping the demo. Could you please create a Expo Snack or any other RN playground with your demo and I will take a look on it. I would prefer to have this reproduction demos online so other people can find them and collaborate if needed.

**Comment by vydimitrov** [comment] 2020-07-24 07:30
Hey @Ajmal0197, I took a look on the code you sent but there are so many references to local files and redux state and it would be impossible for me to get this single file up and running. If you want me to help you, could you please simplify it so I can run the code just by installing dependencies? This is why I suggested creating Expo Snack.

**Comment by Ajmal0197** [comment] 2020-07-24 08:34
> Hey @Ajmal0197, I took a look on the code you sent but there are so many references to local files and redux state and it would be impossible for me to get this single file up and running. If you want me to help you, could you please simplify it so I can run the code just by installing dependencies? This is why I suggested creating Expo Snack.

You have created a great timer...
I have already implemented your timer in various module. The issue is in rare scenario which I have managed with little tweek in my code. So no issue now. Thank you.

**Comment by vydimitrov** [comment] 2020-07-24 08:54
Great, I am happy to read that. Let me know if you need anything else from me :) Closing the issue.

**Closed by vydimitrov** 2020-07-24 08:54 UTC
Labels: Mobile, help wanted

**Comment by timhagn** [comment] 2020-08-20 12:40
Hi there,

thanks for this nifty module @vydimitrov : )! Might I ask you @Ajmal0197, how you got this solved / which tweak you were applying? Cause I'm running into the same issue in a cooperate App (also ejected). I also already nailed it down on the Animated timers, but here I'm stuck right now (and as we have a Go Live on 1st of September, I won't have much time to look into this till then -.-). Any help would be highly appreciated!

Thnx in advance, best,

Tim.

**Comment by vydimitrov** [comment] 2020-08-20 13:15
Hey @timhagn, if you create an ExpoSnack reproducing the issue then I can also take a look on it :)

**Comment by timhagn** [comment] 2020-08-20 14:35
Hola @vydimitrov,

as written above, I have the same problem as @Ajmal0197, I'm working on an ejected corporate App (closed source) am am sparse on time atm. This [PR](https://github.com/facebook/react-native/pull/28841) over at RN should probably fix the problem altogether, but I don't know, when it will be in. The Problem arises, when one has to unmount CCT, or a parent component gets unmounted on page change (likely the OPs issue) or by state change (my issue).

Hope @Ajmal0197 answers with a solution, then I could perhaps provide a patch after solving it. 

Best,

Tim.

**Comment by Ajmal0197** [comment] 2020-08-20 14:45
> Hola @vydimitrov,
> 
> as written above, I have the same problem as @Ajmal0197, I'm working on an ejected corporate App (closed source) and am sparse on time atm. This [PR](https://github.com/facebook/react-native/pull/28841) over at RN should probably fix the problem altogether, but I don't know, when it will be in. The Problem arises, when one has to unmount CCT, or a parent component gets unmounted on page change (likely the OPs issue) or by state change (my issue).
> 
> Hope @Ajmal0197 answers with a solution, then I could perhaps provide a patch after solving it. 
> 
> Best,
> 
> Tim.
> 
> EDIT: Typo.

Can u use useFocusEffect hook of react navigation and wrap it around the countdown component.
 It will mount unmount component every time.

If the above soln don't work then I can send u custom JS file that i have modified.

**Comment by timhagn** [comment] 2020-08-20 14:52
Hi @Ajmal0197,

thanks for the direction towards `useFocusEffect`, will return to this issue on Monday, as I have to direct my attention on other parts of the Project & Publishing the App without the Snackbar (where I'm using CCT) tomorrow. An already changed file would be great, of course : )!

Thanks again,

best,

Tim.

**Comment by Ajmal0197** [comment] 2020-08-20 15:02
> Hi @Ajmal0197,
> 
> thanks for the direction towards `useFocusEffect`, will return to this issue on Monday, as I have to direct my attention on other parts of the Project & Publishing the App without the Snackbar (where I'm using CCT) tomorrow. An already changed file would be great, of course : )!
> 
> Thanks again,
> 
> best,
> 
> Tim.

https://medium.com/@aungmt/react-native-circular-progress-component-using-svg-60bc831e3802
use this with your own setInterval or some library
