### ISSUE TITLE
unable to reset the initialRemainingTime 

### ISSUE THREAD

**Issue by sdbala81** [vydimitrov/react-countdown-circle-timer#48] opened 2020-08-29 02:25 UTC
It seems the initialRemaining time cannot be set programmatically.

Only when the values are hard coded they seem to pick and display the colored and the greyed out area in the timer circle properly 

Suppose if the values had to be set programmatically  for instance, it doesn't seem to pick up.

Use Case - if the user refreshed the page before the duration expiry I need to start from where he left

**Comment by vydimitrov** [comment] 2020-08-29 13:38
Hey @sdbala81, this is by design to avoid any issues computing colors and progress. Check [this recipes in Readme](https://github.com/vydimitrov/react-countdown-circle-timer#change-duration-andor-initialremainingtime-once-component-is-mounted) to find put how you can change `initialRemainingTime`. Let me know if that helps.

**Comment by vydimitrov** [comment] 2020-09-01 07:02
Hey @sdbala81, I am closing this issue, let me know if you need any additional info from me.

**Closed by vydimitrov** 2020-09-01 07:02 UTC
Labels: help wanted
