### ISSUE TITLE
The usage and remaining radians are inconsistent

### ISSUE THREAD

**Issue by 1280103995** [vydimitrov/react-countdown-circle-timer#190] opened 2022-01-12 03:40 UTC
```
<CountdownCircleTimer
  strokeLinecap={"square"}
  duration={100}
  initialRemainingTime={90}
  colors={[["#004777", 0.33], ["#F7B801", 0.33], ["#A30000"]]}
/>
```
<img src="https://user-images.githubusercontent.com/17424486/149058990-b72e46ad-2fc6-4145-9259-f8fdfb44a052.png" width="30%" height="30%"/>

-------------
```
<CountdownCircleTimer
  strokeLinecap={"square"}
  duration={100}
  initialRemainingTime={10}
  colors={[["#004777", 0.33], ["#F7B801", 0.33], ["#A30000"]]}
/>
```
<img src="https://user-images.githubusercontent.com/17424486/149059213-ab145cb2-b135-4e34-825d-b37890214000.png" width="30%" height="30%"/>

I just modified the [demo](https://codesandbox.io/s/tender-bogdan-qd35m?file=/src/index.js) in the readme.

Is this a bug or by design, or am I missing some properties? Anyway, thanks a lot for your library.

**Comment by vydimitrov** [comment] 2022-01-12 07:41
Hey @1280103995, yup, this is how the timer is supposed to work. You set the `duration` of 100 so the full circle will be 100 seconds. Now you want to change the start point and pass `initialRemainingTime` of 90 seconds. So now when the timer renders it will start from a point where 90 seconds are left.

Check also [this one](https://github.com/vydimitrov/react-countdown-circle-timer/tree/master/packages/web#set-the-initial-remaining-time-different-then-the-duration-provided), it may help you to understand the logic.

**Comment by 1280103995** [comment] 2022-01-12 10:02
I mean: in pic 1, the arc length in grey should be equal to the arc length in red (it seems) in pic 2.

**Comment by vydimitrov** [comment] 2022-01-12 10:05
The `initialRemainingTime` determines the arc length in red when the component mounts.

**Comment by 1280103995** [comment] 2022-01-12 10:15
When I change the code to (1 remaining):
```
<div
  className="timer-wrapper"
  style={{ justifyContent: "center", alignItems: "center" }}
  >
    <CountdownCircleTimer
      strokeLinecap={"square"}
      duration={100}
      initialRemainingTime={1}
      colors={[["#004777", 0.33], ["#F7B801", 0.33], ["#A30000"]]}
    />
    <div
       style={{
          height: "100%",
          width: 1,
          backgroundColor: "pink",
          position: "absolute"
       }}
    />
</div>
```
The effect obtained is as follows:
<img width="30%" height="30%" src="https://user-images.githubusercontent.com/17424486/149120668-91b6d6df-5aba-4e2e-80ff-f71e5b531e00.png">


It seems that some arc length is added.

Is this a bug in SVG?

**Comment by vydimitrov** [comment] 2022-01-12 10:22
I see, so your concern is that small piece on the right side of the pink line?

**Comment by 1280103995** [comment] 2022-01-12 10:30
Yes. But there is also on the left.

**Comment by vydimitrov** [comment] 2022-01-12 10:31
The part on the left is the remaining time that you pass with `initialRemainingTime={1}`, This is 1 second left from the 100 seconds you pass a duration.

**Comment by 1280103995** [comment] 2022-01-12 10:35
So the correct effect should be: in the case of the remaining 1, only draw a little arc length to the left of the pink line.

**Comment by 1280103995** [comment] 2022-01-12 10:37
I've been troubleshooting all day today, it should be an SVG bug, I'll continue tomorrow.

**Comment by vydimitrov** [comment] 2022-01-12 10:41
> So the correct effect should be: in the case of the remaining 1, only draw a little arc length to the left of the pink line.

Yes, that is correct. At this moment, I do not have any clue why it move a bit to the right. I will try to investigate it. Is this critical issue for you? This is really the first time I see it.

**Comment by vydimitrov** [comment] 2022-01-12 10:41
Preproduction demo here - https://codesandbox.io/s/busy-brook-3fmyz?file=/src/index.js

**Comment by vydimitrov** [comment] 2022-01-12 11:58
I think I found it, the path starting point needs to be moved with half of the width of the path. Like so

Before `d="m 90,6 a 84,84 0 1,0 0,168 a 84,84 0 1,0 0,-168"`
After `d="m 84,6 a 84,84 0 1,0 0,168 a 84,84 0 1,0 0,-168"`

At first look it seems that to fix it we will need a custom path for the circle and not using arches as above, which I am not sure it is worth doing it.

**Comment by 1280103995** [comment] 2022-01-13 01:11
> > So the correct effect should be: in the case of the remaining 1, only draw a little arc length to the left of the pink line.
> 
> Yes, that is correct. At this moment, I do not have any clue why it move a bit to the right. I will try to investigate it. Is this critical issue for you? This is really the first time I see it.

The problem exists in my production app, but it doesn't affect much. Just a UI issue.

**Comment by 1280103995** [comment] 2022-01-13 01:13
I tried to implement the same progress bar using react-native-svg, same problem.

**Comment by vydimitrov** [comment] 2022-01-13 08:11
Yup, it is the same logic to render the path. I am not sure if I am going to fix it since it is very tricky. If that is such a big problem one idea is to rotate the path so it matches the start point.

I will check if I can come up with some formula to calculate the start point and the arches based on the path width but can't promises anything.

**Comment by vydimitrov** [comment] 2022-01-17 07:35
Here is a workaround you can use for now. https://codesandbox.io/s/busy-brook-3fmyz?file=/src/index.js

The angle that we rotate the path to match the start very much depends of the stroke width. So this is not a solution that is going to work in every case. 

```js
React.useEffect(() => {
    document.querySelectorAll("path")[1].style.transform =
      "translate(90px, 90px) rotate(-4deg) translate(-90px, -90px)";
  }, []);
```

**Comment by 1280103995** [comment] 2022-01-20 08:55
This method is great, thank you for your work.

I would like to know why their arc lengths are different when the initialRemainingTime is 1 and when it is 99.  :)

**Comment by vydimitrov** [comment] 2022-01-20 11:03
The arch lengths is the same - you can read more on how the animation works here - https://css-tricks.com/svg-line-animation-works/

**Comment by 1280103995** [comment] 2022-01-21 03:17
I'm not good at using svg, but I'll learn it later.

---------------------------------

<img width="70%" height="70%" src="https://user-images.githubusercontent.com/17424486/150458062-d2236817-77d1-49cc-b3aa-f425a2f5dc15.png">

In fact, I use this component as a progress bar.

As you can see from the picture, in the left picture, the gray arc length is less than the navy blue arc length in the right picture.

Since their arc lengths are both 10, the lengths should be equal. That's what I'm asking about this issue.

**Comment by vydimitrov** [comment] 2022-01-21 08:27
Ooo now I see what you mean... this is very interesting... I will try to dig in the code to see if I can figure out why is that. The function that calculates the arch is the same.

**Comment by vydimitrov** [comment] 2022-01-21 08:36
I guess it has something to do with the fact that we rotated the path. Check here without rotation. In both cases seems symmetrical.  https://codesandbox.io/s/busy-brook-3fmyz?file=/src/index.js

![image](https://user-images.githubusercontent.com/10707142/150493813-758375dc-9de1-414c-bfbe-008377f8eeb9.png)
![image](https://user-images.githubusercontent.com/10707142/150493846-042666c3-b798-4672-b25a-4476762b9cb1.png)

**Comment by NWPoul** [comment] 2022-01-26 18:06
How can I modify an svg so with "square" stroke it's starts(ends) at the "12 o'clock" instead of being exceeded to the right?
This lead to noticeable lag in visual start of the timer's circle in case of "square" option for stroke(

**Comment by vydimitrov** [comment] 2022-01-26 19:16
@NWPoul, did you see this one? https://github.com/vydimitrov/react-countdown-circle-timer/issues/190#issuecomment-1014221159

**Comment by NWPoul** [comment] 2022-01-26 20:24
> @NWPoul, did you see this one? 

Yes but thought it was about the arc length
and all what I managed to achieve with it - is shifting circle from it's starting ponits... I am not strong with SVG😇

**Comment by vydimitrov** [comment] 2022-01-26 21:52
You will need just to add the one below to your timer component and adjust the rotation angle based on the `strokeWdith`

```js
React.useEffect(() => {
    document.querySelectorAll("path")[1].style.transform =
      "translate(90px, 90px) rotate(-4deg) translate(-90px, -90px)";
  }, []);
```

**Comment by NWPoul** [comment] 2022-01-27 08:16
> You will need just to add the one below to your timer component and adjust the rotation angle based on the `strokeWdith` and may be the `translate` style, which is half of the `size` prop you pass to the component, by default it is 180.

Thank you for the answer!
Yes after ajusting "translate" circle don't shift aside
but now stroke starts mooving exeeded to the left on @starting point" so the lag still there
desides the start line now tilted relative to vertical axis(
![image](https://user-images.githubusercontent.com/28613875/151318929-93a5b221-a7db-4768-8325-2fb053168e71.png)

**Comment by NWPoul** [comment] 2022-01-27 09:14
UPD:
After RTFM for SVG seems that mine (and probably others) problem solwing is easy - just chose "butt" for stroke-linecap prop)

**Comment by vydimitrov** [comment] 2022-01-28 08:06
@NWPoul this is genius... I really did not think about it. This really solved the problem. It seems I will need to extend the `strokeLinecap` prop type to support `butt` so TS is happy.

**Comment by vydimitrov** [comment] 2022-01-29 12:06
'butt' option was added in v3.0.8. @1280103995 please test it and let me know if we can close the bug.

**Comment by vydimitrov** [comment] 2022-02-04 07:57
I am closing this one. Let me know if you have any further questions.

**Closed by vydimitrov** 2022-02-04 07:57 UTC
Labels: bug, web

**Comment by 1280103995** [comment] 2022-02-11 06:28
sorry I'm late. I took a long vacation.

Now v3.0.8 solved my problem.

@NWPoul @vydimitrov Thank you so much!
