### ISSUE TITLE
How can I change timer's attributes while it is running?

### ISSUE THREAD

**Issue by ropinheiro** [vydimitrov/react-countdown-circle-timer#28] opened 2020-06-16 17:16 UTC
I'm trying to control the `CountdownCircleTimer` in some more controlled way, as I need the same Timer to have distinct behaviors depending on the current time. E.g. if near some meeting date, the Timer renders with some rules, if not near, the Timer renders with other rules. And inside the proximity of a meeting, the Timer has different behaviors depending on the proximity in time.

This means that I need to be able to change `trailColor`, `colors` and `duration` at specific points in time, all this controlled by a parent component.

I have successfully did that but the problem is that I'm running in issues like this one:

![image](https://user-images.githubusercontent.com/19519494/84806134-232d9d00-affd-11ea-8e53-84ca49b0e587.png)

Because the information is in the parent TimerField's state, when that state is changed and it happens that the `CountdownCircleTimer` is being rendered, then I get this error. This is more easily reproducible if we pass parent functions that sets state as parameters of `renderTime`, then execute them inside `renderTime` after doing some test (e.g. testing if the countdown reached some value).

Is that a known issue? Can't I freely manipulate the `CountdownCircleTimer` attributes after Timer is started?

**Comment by vydimitrov** [comment] 2020-06-16 18:19
You can change all of the above listed props while the timers is running, the only one that you can not change is `duration`. To change the duration you will need to do [this](https://github.com/vydimitrov/react-countdown-circle-timer/tree/master/packages/web#restart-timer-at-any-given-time)

**Comment by ropinheiro** [comment] 2020-06-16 18:54
Yes, it worked! Thank you!

There is a red warning appearing when the first cycle finishes and before the second cycle starts. It doesn't happen after this:

```
index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in CountdownCircleTimer
```

It points to the first line of the `CountdownCircleTimer`, but everything seems working properly. It passes a parent function to the onComplete attribute. This function then sets two state values, first the one that sets the duration, then the second sets the key (so that when the component detects the key changing, it has the duration already set).

Not sure why it only happens when passing from the 1st cycle to the 2nd cycle, but apparently it seems to be working in the browser.

Nonetheless

**Comment by vydimitrov** [comment] 2020-06-17 07:32
Could you please create Codesandbox with the issue and I will take a look on it? It seems some `setState` is fired once the component is unmounted.

**Comment by ropinheiro** [comment] 2020-06-17 08:42
Sure, here it is: https://codesandbox.io/s/charming-hawking-4zwyy?file=/src/App.js

Not sure why, but I see different things here, although the problem sees to have a similar origin: the execution of  `onComplete`.

In my laptop I see a **red warning** `"Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function."` **only in the first onComplete execution**.

But in the Code Sandbox, I see an **uncaught error** `"Cannot remove node {number} because no matching node was found in the Store"` in **every onComplete execution**.

**Comment by vydimitrov** [comment] 2020-06-17 10:44
I see, I will investigate it. One thing you can do tho, if you are going to change the `key` in the `onComplete` callback and restart animation, then you don't need to return an array from `onComplete`. Once the `key` is new, the component will be unmounted and new instance will be initialized and the animation will start over. Thus, you won't see the warning. Also there is no point to return anything from `onComplete` since the moment the `key` is changed `onComplete` is cancelled. 

```jsx
  function setTimerTo(duration, newMode, color) {
    setTimerDuration(duration);
    setTimerMode(newMode);
    setCircleColor(color);
    return [true, 250]; <---- you don't need to do that, just don't return anything 
  }
```

**Comment by ropinheiro** [comment] 2020-06-17 11:33
Good catch! By removing all those superfluous `returns`, I no longer see `red warnings` in my dev environment. Thank you!

I also removed the `returns` in the Code Sandbox and I still see the `uncaught errors`. Maybe it's something I messed up when removing unrelated code, or something specific of the Code Sandbox. I reviewed the code and for all that matters, I'm pretty sure it's the same code. I also checked that both are using the 2.2.0 version of the `react-countdown-circle-timer`. I also changed all dependencies in the Code Sandbox to match the versions I'm using here, just as sanity check. Same results.

Feel free to close this issue if you don't want to waste more time on this, as I got it working with no warnings and errors in my real environment. The fact that it is throwing errors in the Code Sandbox is now some curiosity, but for me not urgent (you may still feel it's important for you because it's your component, after all).

If you really want to dig in and solve this, I will have an eye on it as I'm also curious to understand what's happening :)

**Comment by vydimitrov** [comment] 2020-06-17 12:26
I just checked your last CodeSandbox and I don't see any errors in the console there, it works like a charm. It may be some cache issue with CodeSandbox. Can you try to run in incognito mode or some diffeent browser?

**Comment by vydimitrov** [comment] 2020-06-17 12:28
I will keep this bug open to investigate why a wraning is triggered when `onComplete` returns an array, indicating that the animation should repeat, and the component is unmounted at the same time.

**Comment by ropinheiro** [comment] 2020-06-17 13:49
Yes, I confirm that in incognito mode, the error disappears! It seems it was just cache, then.

**Comment by ropinheiro** [comment] 2020-06-17 13:50
Correction: when I opened it, it gave me no errors. But when I pressed this refresh button:

![image](https://user-images.githubusercontent.com/19519494/84906463-deac0b00-b0a9-11ea-97a3-bac1bf1665ee.png)

It happened again:

![image](https://user-images.githubusercontent.com/19519494/84906490-ea97cd00-b0a9-11ea-8c95-00657c2e109c.png)

One for each timer cycle.

**Comment by ropinheiro** [comment] 2020-06-17 13:54
I tested it again: closed the browser. Opened in incognito mode. Pasted the URL in the address input. No errors, timer working like a charm. Then clicked the Code Sandbox's refresh button (no changes in the code). Timer working functionally good, but with errors in the console, one for each onComplete execution.

**Comment by vydimitrov** [comment] 2020-06-17 14:18
Nope, it is still fine for me. Even after hitting the Code Sandbox's refresh button no errors in the console. I will consider the Code Sandbox issue as outside the component. 

Can you check this one - https://codesandbox.io/s/affectionate-sid-w6v2v?file=/src/App.js
Even with the following code there is no error this time:
```
function setTimerTo(duration, newMode, color) {
    setTimerDuration(duration);
    setTimerMode(newMode);
    setCircleColor(color);
    return [true, 250]; <---- I added this one back just for the test
  }
```

**Comment by vydimitrov** [comment] 2020-06-17 14:24
There is definitely something wrong with Code Sandbox, I will test it on my own test environment and see if I can reproduce it.

**Comment by ropinheiro** [comment] 2020-06-17 14:45
I tested the Code Sandbox link you provided.
Here is what console shows just after I paste the URL in a freshly opened incognito Chrome:

![image](https://user-images.githubusercontent.com/19519494/84912491-65181b00-b0b1-11ea-9c4e-2ac47d8291fd.png)

Now after clicking the refresh button and waiting for some cycles to complete:

![image](https://user-images.githubusercontent.com/19519494/84912622-84af4380-b0b1-11ea-90e4-ac4b4fb45998.png)

**Comment by ropinheiro** [comment] 2020-06-17 14:48
Now using Firefox, same sequence:

![image](https://user-images.githubusercontent.com/19519494/84912933-deb00900-b0b1-11ea-84fd-b6459afba673.png)

Then after refresh:

![image](https://user-images.githubusercontent.com/19519494/84913025-f8515080-b0b1-11ea-8d70-c4b860dbdea0.png)

So it's now browser, and it's not cache (as it was the first time I opened this in Firefox, at least this week - I usually use Chrome).

**Comment by vydimitrov** [comment] 2020-06-17 16:14
I see, okay, it seems there is an issue when we attempt to repeat the animation while we are changing the component key / unmounting the component. I will keep this bug open to investigate that issue. Thank you for taking your time to report and reproduce this issue for me :)

**Comment by ropinheiro** [comment] 2020-06-17 17:47
Never mind, it's me that thanks you for developing this nice component and also answering all my (some of them silly) questions 👍 Feel free to request additional information from me to help you on this.

**Closed** 2020-06-21 07:04 UTC
Labels: Web, help wanted

**Comment by vydimitrov** [comment] 2020-06-21 07:14
Hey @ropinheiro, the issue with the warning is now fixed. Here is the origin commit that fixes it - https://github.com/vydimitrov/use-elapsed-time/commit/3afeae6d01505be9fe9d7d370b20154d5c07606e

If you have time please retest it and let me know the result. Thank you!

**Comment by ropinheiro** [comment] 2020-06-22 09:04
I re-tested it, by upgrading all packages and adding the `return [true, 250]; ` again in the `setTimerTo` here:

https://codesandbox.io/s/charming-hawking-4zwyy?file=/src/App.js

I confirm that the warning no longer appears, so it seems to be positively fixed 👍 

Only those `uncaught errors`, one per cycle, as mentioned before, continue to appear.

![image](https://user-images.githubusercontent.com/19519494/85269320-9ad15100-b46f-11ea-97a4-c632ab351752.png)

But not in my installation. Only on CodeSandbox, as before.

**Comment by sergiocardoso** [comment] 2020-08-12 18:24
> You can change all of the above listed props while the timer is running, the only one that you can not change is `duration`. To change the duration you will need to do [this](https://github.com/vydimitrov/react-countdown-circle-timer/tree/master/packages/web#restart-timer-at-any-given-time)

Hi vydimitrov, thanks for this amazing plugin. Sorry for my english, but please I have a question: how can I do to change the duration after timer start? I don't understand. 

Thank you =)

**Comment by vydimitrov** [comment] 2020-08-12 18:36
@sergiocardoso, please check [this demo](https://codesandbox.io/s/dreamy-bose-xch4c?file=/src/index.js) and let me know if that is helpful. Check how I am passing a new `key` and `duration` props to the component when I click the button.
