### ISSUE TITLE
Larger strokeWidth doesn't render properly

### ISSUE THREAD

**Issue by haydenbleasel** [vydimitrov/react-countdown-circle-timer#55] opened 2020-10-03 04:19 UTC
Running in React Native + Expo on iPhone 11 Pro.

Changing the `strokeWidth` to anything above `16` results in the stroke not being masked correctly.

![Screen Shot 2020-10-03 at 2 16 39 pm](https://user-images.githubusercontent.com/4142719/94983135-2c7a4f80-0583-11eb-9f03-c561a54dc2fc.jpeg)

**Comment by vydimitrov** [comment] 2020-10-04 08:50
Hey, the active path is not masked but rather part of it shown using `stroke-dashoffset` as described [here](https://css-tricks.com/svg-line-animation-works). This seems to be a rendering issue. 

Any idea on how to fix it or PR will be very welcomed :)

**Comment by vydimitrov** [comment] 2020-10-25 11:24
Hey @haydenbleasel, I am not able to reproduce it. I tested it on iPhone 11 and it works just fine. Please refer to the image below where the stroke width is 40.

I am closing this issue for now. 

![83557](https://user-images.githubusercontent.com/10707142/97105637-bae27c80-16bc-11eb-91d7-08c48ac05e6e.jpg)

**Closed by vydimitrov** 2020-10-25 11:24 UTC
Labels: bug, mobile
