### ISSUE TITLE
Timer holds/pauses countdown when there is state update

### ISSUE THREAD

**Issue by thesheikhwasim** [vydimitrov/react-countdown-circle-timer#72] opened 2021-01-03 05:37 UTC
I used this library to show the timer on my apps quiz module.
The quiz is displayed on UI (1 question at a time). There are user clicks on NEXT-PREV and answer selection and state updates. Whenever I click on any state update click actions, the running timer pauses until state updates. 

How did I confirm more?
- I did a back to back click on answers and found that the timer was stopped until I stopped selecting answers.

Video file attached: 

https://user-images.githubusercontent.com/31923278/103472460-d7352080-4db3-11eb-9910-84ddc76a691c.mp4

**Comment by vydimitrov** [comment] 2021-01-04 08:23
Hey, could you please share some code via Expo Snack, for exmaple, so I can take a look on it?

**Comment by vydimitrov** [comment] 2021-01-14 07:56
I am closing this one for now, since I am not able to reproduce it. Let me know if I can help you in any other way.

**Closed by vydimitrov** 2021-01-14 07:56 UTC
Labels: help wanted, mobile

**Comment by maacofficial** [comment] 2021-03-04 15:25
I have the same issue how can i solve this problem?
